<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sysadm-PC" ignored="0" name="Profile" tests="2" failures="1" timestamp="13 Mar 2019 11:28:36 GMT" time="206.82" errors="0">
  <testcase name="accountProfile" time="99.818" classname="testScriptsAccounts.Profile">
    <skipped/>
  </testcase> <!-- accountProfile -->
  <testcase name="accountProfile" time="99.634" classname="testScriptsAccounts.Profile">
    <failure type="java.lang.AssertionError" message="Profile saved successfully">
      <![CDATA[java.lang.AssertionError: Profile saved successfully
	at domainServices.Accounts.testEditProfileChanges(Accounts.java:203)
	at testScriptsAccounts.Profile.accountProfile(Profile.java:36)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- accountProfile -->
</testsuite> <!-- Profile -->
