<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="sysadm-Latitude-3480" ignored="0" name="Account_Service_Flyin_SocialSignUp" tests="2" failures="1" timestamp="04 May 2020 05:15:15 GMT" time="0.821" errors="0">
  <testcase name="Flyinsocialsignup" time="0.403" classname="accountsAPI.Account_Service_Flyin_Social_Signup">
    <skipped/>
  </testcase> <!-- Flyinsocialsignup -->
  <testcase name="Flyinsocialsignup" time="0.369" classname="accountsAPI.Account_Service_Flyin_Social_Signup">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at accountsAPI.AccountsCommon_API.validation(AccountsCommon_API.java:1121)
at accountsAPI.Account_Service_Flyin_Social_Signup.Flyinsocialsignup(Account_Service_Flyin_Social_Signup.java:20)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 10 stack frames]]>
    </failure>
  </testcase> <!-- Flyinsocialsignup -->
</testsuite> <!-- Account_Service_Flyin_SocialSignUp -->
