<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Payment UI Validation"
           tests="4"
           failures="2"
           errors="0"
           skipped="2"
           time="2.431">
  <properties />
            <testcase name="afterMethod" time="0.030" classname="paymentsUI.PaymentUI_AddStoredCardAndValidate">
                <failure type="java.lang.NullPointerException"
                  message="(null)"
              >
<![CDATA[java.lang.NullPointerException
  org.openqa.selenium.remote.Augmenter.extractRemoteWebDriver(Augmenter.java:72)
  org.openqa.selenium.remote.BaseAugmenter.augment(BaseAugmenter.java:96)
  common.CommonUtil.screenshot(CommonUtil.java:179)
  common.CommonUtil.afterMethod(CommonUtil.java:142)
  paymentsUI.PaymentUI_AddStoredCardAndValidate.afterMethod(PaymentUI_AddStoredCardAndValidate.java:96)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
  org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
  org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
  org.testng.internal.Invoker.retryFailed(Invoker.java:839)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
            <testcase name="addSCandVerifyIfAdded" time="0.875" classname="paymentsUI.PaymentUI_AddStoredCardAndValidate">
                <failure type="java.lang.AssertionError"
                  message="(null)"
              >
<![CDATA[java.lang.AssertionError
  org.junit.Assert.fail(Assert.java:92)
  org.junit.Assert.assertTrue(Assert.java:43)
  org.junit.Assert.assertTrue(Assert.java:54)
  paymentsUI.PaymentUI_AddStoredCardAndValidate.addSCandVerifyIfAdded(PaymentUI_AddStoredCardAndValidate.java:89)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.retryFailed(Invoker.java:839)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
            <testcase name="tearDown" time="0.0" classname="paymentsUI.PaymentUI_AddStoredCardAndValidate">
          <skipped />
    </testcase>
            <testcase name="addSCandVerifyIfAdded" time="0.0" classname="paymentsUI.PaymentUI_AddStoredCardAndValidate">
          <skipped />
    </testcase>
  
  
</testsuite>
