<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="API ADCB"
           tests="2"
           failures="1"
           errors="0"
           skipped="1"
           time="1.371">
  <properties />
            <testcase name="adcb_Pay" time="0.031" classname="paymentsAPI.API_Reward_ADCB_Pay">
                <failure type="junit.framework.AssertionFailedError"
                  message="(null)"
              >
<![CDATA[junit.framework.AssertionFailedError
  junit.framework.Assert.fail(Assert.java:48)
  junit.framework.Assert.assertTrue(Assert.java:20)
  junit.framework.Assert.assertTrue(Assert.java:27)
  paymentsAPI.API_PaymentCommon1.validation(API_PaymentCommon1.java:1684)
  paymentsAPI.API_Reward_ADCB_Pay.adcb_Pay(API_Reward_ADCB_Pay.java:28)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
  org.testng.internal.Invoker.retryFailed(Invoker.java:839)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  java.lang.Thread.run(Thread.java:748)
]]>
      </failure>

          </testcase>
  
            <testcase name="adcb_Pay" time="0.0" classname="paymentsAPI.API_Reward_ADCB_Pay">
          <skipped />
    </testcase>
  
  
</testsuite>
