<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="sysadm-Latitude-3480" name="paymentsAPI.API_Reward_ADCB_Pay" tests="2" failures="1" timestamp="05 Mar 2020 05:12:34 GMT" time="1.371" errors="0">
  <testcase name="adcb_Pay" time="0.031" classname="paymentsAPI.API_Reward_ADCB_Pay">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:48)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at paymentsAPI.API_PaymentCommon1.validation(API_PaymentCommon1.java:1684)
at paymentsAPI.API_Reward_ADCB_Pay.adcb_Pay(API_Reward_ADCB_Pay.java:28)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- adcb_Pay -->
  <testcase name="adcb_Pay" time="1.340" classname="paymentsAPI.API_Reward_ADCB_Pay">
    <skipped/>
  </testcase> <!-- adcb_Pay -->
</testsuite> <!-- paymentsAPI.API_Reward_ADCB_Pay -->
